name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      WEB_APP_NAME: snappies-backend-dev

    environment: all
    steps:
      - uses: actions/checkout@v3

      - name: Set DATABASE_URL
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Create .env file
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag pfe_back:pfe_back_dev

      - name: Check Azure CLI version
        run: az --version

      - name: Debug Azure Credentials
        run: echo "${{ secrets.AZURE_CREDENTIALS }}"

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v2
        with:
          app-name: $WEB_APP_NAME
          images: pfe_back:pfe_back_dev
