name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    

jobs:
  build:
    runs-on: ubuntu-latest

    environment: all
    steps:
      - uses: actions/checkout@v3

      - name: Set DATABASE_URL
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Create .env file
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env

      - name: Build the Docker image
        run: docker build . -t pfe_back:pfe_back_dev

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: redarmsii/pfe_back:pfe_back_dev

      - name: Deploy to Azure App Service
        uses: Azure/webapps-deploy@v2
        with:
          app-name: snappies-backend-dev
          images: docker.io/redarmsii/pfe_back:pfe_back_dev


