name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    environment: all
    steps:
    - uses: actions/checkout@v3
    
    - name: Set DATABASE_URL
      run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
      
    - name: Create .env file
      run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:pfe_back
