# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - snappies-backend-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://pfebackend.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9e13c6858f524b19af7f8dff49c576b7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e08ed5c2a4684b98a99e4b01da7e9d6b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: pfebackend.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9e13c6858f524b19af7f8dff49c576b7 }}/pfe_back:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'snappies-backend-prod'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9a1511db13ed4273b5460fa96c2a6108 }}
        images: 'pfebackend.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9e13c6858f524b19af7f8dff49c576b7 }}/pfe_back:${{ github.sha }}'