# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - snappies-backend-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://pfebackend.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_72456b77c9f247dca0079236bebb969a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ef4fad34f8c8480d8925dac09ebf2b1b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: pfebackend.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_72456b77c9f247dca0079236bebb969a }}/pfe_back:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'snappies-backend-prod'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_76bc279a5f7543cbb090d8f815387e02 }}
        images: 'pfebackend.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_72456b77c9f247dca0079236bebb969a }}/pfe_back:${{ github.sha }}'