name: Rust

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    environment: all
    steps:
    - uses: actions/checkout@v3

    - name: Set DATABASE_URL
      run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

    - name: Set PORT
      run: echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV

    - name: Run tests
      run: cargo test --verbose

    - name: Build
      run: cargo build --verbose

    - name: Cargo Fix
      run: cargo fix --verbose --allow-dirty --workspace
