name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions/setup-rust@v1  # Utilisez v1 au lieu de v2
      with:
        rust-version: 1.56.0

    - name: Install dependencies
      run: |
        sudo apt-get install libpq-dev  # Installez les dépendances nécessaires pour SQLx avec PostgreSQL
        cargo build --verbose
        cargo test --verbose

    - name: Run SQLx migrations
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        cargo install sqlx-cli
        sqlx migrate run

    - name: Run additional checks or tasks
      run: |
        # Ajoutez ici d'autres étapes nécessaires, comme la vérification du style de code, les linters, etc.
